### PR TITLE
Fix issues surrounding store reference tracking.

### LINKED ISSUE #119: Weird missing CSS bug
@TeffenEllis I can’t figure out what’s going on here, hopefully you can help.

Repro:

1. Visit [https://eager.io/blog/introducing-embedbox-open-source-embed-code-ui/](https://eager.io/blog/introducing-embedbox-open-source-embed-code-ui/).
2. Click the modal demo button.
3. Close the modal.
4. Click the WordPress target entry in the inline demo.
5. Observe:

### PR DESCRIPTION
**Pull request by TeffenEllis**
Closes #119

### CODE REVIEW

File: app/embed-box-base.js [hunk 1]
```diff
@@ -54,17 +52,6 @@ export default class EmbedBoxBase {
       targets: targetConfigs = {}
     } = spec
 
-    // HACK: Custom targets have a different BaseComponent instance.
```
Comment (TeffenEllis) [inline app/embed-box-base.js]: Nothing like removing past `HACK` comments 😉

Comment (adamschwartz) [inline app/embed-box-base.js]: Also nothing like a PR fix with:

```diff
+29
-29
```

👍
